"""
Django settings for bumper2 project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rwwdxfc(!8^+v!yh(0xrptn^rf!)j$b=%t%7kn0b90*i%_vv9@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
BUMPER_ENV = 'PROD'

ALLOWED_HOSTS = ['*']
ADMINS = (
    ('Inderjeet', 'inderjeet@autoninja.in'),
)

MANAGERS = ADMINS

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "push_notifications",
    "djcelery",
    'core',
    'simple_history',
    'multiselectfield',
    'rest_framework',
    'rest_framework.authtoken',
    'social.apps.django_app.default',
    'rest_framework_docs',
    'drf_multiple_model',
    'rest_framework_swagger',
    'opbeat.contrib.django',
    'imagekit',
    'mathfilters',
    # 'django_extensions' # - for generating erd diagram
)
AUTH_USER_MODEL = 'core.BumperUser'

AUTHENTICATION_BACKENDS = (
    'social.backends.google.GoogleOAuth2',
    'social.backends.twitter.TwitterOAuth',
    'social.backends.facebook.FacebookOAuth2',
    'core.authBackend.AuthBackend',
    # 'django.contrib.auth.backends.ModelBackend', // disabling the username based login.
)

MIDDLEWARE_CLASSES = (
    'opbeat.contrib.django.middleware.OpbeatAPMMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'bumper2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'static')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]
TEMPLATES[0]['OPTIONS']['context_processors'].append("core.context_processors.static_file_version_processor")

WSGI_APPLICATION = 'bumper2.wsgi.application'

"""
Note: If you are planning on running your project with DEBUG=True, then make sure you have set the development
certificate as your APNS_CERTIFICATE. Otherwise the app will not be able to connect to the correct host.
Docs: https://pypi.python.org/pypi/django-push-notifications/1.2.1
"""

PUSH_NOTIFICATIONS_SETTINGS = {
    "GCM_API_KEY": "AIzaSyDv045E6Z3sZ-915Kf5XqhvR4cWPYAz8kM",
    "APNS_CERTIFICATE": "/srv/www/bumper2/deployment/bumperProd.pem",
}

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bumper2',
        'USER': 'ninja',
        'PASSWORD': 'BumPer@(!!',
        'HOST': 'bumper-prod.cqmmrkoey5ra.ap-southeast-1.rds.amazonaws.com',
    },
    'bumperv1': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bumper',
        'USER': 'ninja',
        'PASSWORD': 'BumPer@(!!',
        'HOST': 'localhost',
    },
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

APPEND_SLASH = True

MEDIA_ROOT = 'media'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

STATIC_FILES_VERSION = '1.3.26'  # this is what is to be used after url?v=
WEB_STATIC_FILES_VERSION = '1.2.32'  # this is what is to be used after url?v=

PROCESS_IN_ASYNC = True
ALERT_EMAIL_PAYMENT_FAILURE_TO_LIST = ['inderjeet@bumper.com']
ALERT_EMAIL_PAYMENT_FAILURE_CC_LIST = ['akhil@bumper.com','anuj@bumper.com','ashvin.sharma@bumper.com',
                                       'mudit.mittal@bumper.com','tanvi.gupta@bumper.com','shonalee@bumper.com',
                                       'praveena@bumper.com','pravin.raj@bumper.com','deepakraj@bumper.com',
                                       'veeresh@bumper.com']

PAYMENT_URL = "https://bumper.com/payment/?booking_id=%s&utm_source=payment"

WARNING_TIME_OTP_NOT_VALIDATED = 60

ALERT_SMS_PAYMENT_SUCCESSFUL = [
    # '8800165656',  # Inderjeet
    '8296967791',  # Tanvi
    '9740884757',  # Shonalee
    '9740355886',  # Khaja
    '9818235678',  # Ankit
    '9953287898',  # Sharad Ji
]

ALERT_QUICK_PICKUP = [
    '8800165656',  # Inderjeet
    '8296967791',  # Tanvi
    '9923879540',  # Amar
    '7349213255',  # Pratap
    '9871995123',  # Mudit
    '9880623342',  # Akhil
    '9901953011',  # Ashvin
    '9953287898',  # Sharad Ji
]

BUMPER_SUPPORT_NUM = '9108446586'
BUMPER_SUPPORT_EMAIL = 'bumpercare@bumper.com'
BUMPER_APP_URL_FOR_APP_INSTALL = 'http://bit.ly/hitbumper'
BUMPER_APP_URL_THROUGH_APP_REDIRECT_URL = 'https://bumper.com/?booking_id=%s&utm_source=appredirecturl&utm_medium=website&utm_campaign=appinstall'
SHOW_CHAT_OPTION = True
CHAT_OPTION_TO_SHOW = 'intercom'  # [intercom/ freshchat]

DATE_INPUT_FORMATS = ('%d-%b-%Y', '%Y-%m-%d', '%d-%m-%Y')
BILL_UPLOAD_ALLOWED_EXTENSIONS = [".jpg", ".png", ".tiff", ".jpeg", ".pdf"]
BILL_UPLOAD_MAX_SIZE_PER_FILE = 1024*1024*7 # 1mb
DENT_IMAGE_UPLOAD_MAX_SIZE_PER_FILE = 1024*1024*10 # 1mb
SMS_FAILURE_ALERT_LIST = ['inderjeet@autoninja.in', 'ashvin.sharma@autoninja.in', 'anuj@autoninja.in']
SMS_DEFAULT_VENDOR = 'INFINIA'
SMS_DND_LIST = [
    '9886452736'  # Ashvin's Wife
]

CITRUS_MERCHANT_ACCESS_KEY = 'FN22MPAUSX5E7LD8NKIB'
CITRUS_MERCHANT_SECRET_KEY = '61915d27681c2e25b626e792271dd888264248ef'
CITRUS_RETURN_URL = 'http://booking.bumper.com/payment/citrus-pay/'
CITRUS_WEBSITE_RETURN_URL = 'http://booking.bumper.com/payment/citrus-pay-web/'
CITRUS_VANITY_URL = 'd6flya8ws0'
CITRUS_FORM_POST_URL = "https://citruspay.com/%s" % CITRUS_VANITY_URL
TXNID_APPEND_TEXT = 'BUMP'

CITRUS_MERCHANT_STAGING_ACCESS_KEY = 'ATJP15ZY1GDG0VAAHQXX'
CITRUS_MERCHANT_STAGING_SECRET_KEY = 'e048d67c7541fd422cec0395e50169d1ed422e0f'

RAZOR_PAY_API_KEY = 'rzp_live_wKgCYUEk3SZnm7'
RAZOR_PAY_API_SECRET = 'DgPF3LQM2eoDDhORjJH6gVSK'

PAYTM_MERCHANT_KEY = 'BuVnxwnLOi8LJnFf'
PAYTM_MERCHANT_ID = '5c327672-59e5-4a71-92a0-c0d7e910f4ca'
PAYTM_SALES_WALLET_GUID = "02d796c4-15d8-4559-8e37-68ad62e53e1d"
PAYTM_BASE_URL = 'https://trust.paytm.in'
PAYTM_WALLET_NAME = "BUMPER.COM"

# CELERY SETTINGS
BROKER_URL = 'redis://localhost:6379/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'
USE_CELERY_FOR_SYNC = True

EMAIL_BACKEND = 'django_ses.SESBackend'
AWS_SES_REGION_NAME = "eu-west-1"
AWS_SES_REGION_ENDPOINT = "email.eu-west-1.amazonaws.com"
AWS_ACCESS_KEY_ID = 'AKIAIT23B5QMUZZMX7GA'
AWS_SECRET_ACCESS_KEY = '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'

GOOGLE_ANALYTICS_UNIVERSAL_KEY = "UA-66242481-1"
LOCALYTICS_KEY = "c19c8aec634666c0fc989e5-5bcebcee-44f8-11e6-4593-00adad38bc8d"

EMAIL_HOST = 'email-smtp.eu-west-1.amazonaws.com'
EMAIL_HOST_USER = 'AKIAISG6R3E7NQQYXWQQ'
EMAIL_HOST_PASSWORD = 'AtMAPMMcc8S9AO1FsFB3qE39Q/bgCAxihS9TzV3T2ZQV'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
SERVER_EMAIL = 'inderjeet@bumper.com'
DIRECT_PAYMENT_URL_BASE = 'https://bumper.com/direct-payment/?pid=%s'
BASE_URL = 'http://booking.bumper.com/'
FEEDBACK_BASE_URL = 'https://bumper.com/feedback/?token=%s'
BASE_URL_WEB = 'https://bumper.com/'

DENT_IMAGE_THRU_GMAIL = False

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'PAGE_SIZE': 100,
    'EXCEPTION_HANDLER': 'api.exc_handler.exception_handler',
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    #'DEFAULT_PAGINATION_CLASS' : 'api.custom_paginations.PageNumberPaginationDataOnly',
}

JWT_AUTH = {
    'JWT_VERIFY_EXPIRATION': False,
}

BOOKING_TOKEN_SECRET = '2f2276@13b7!4c76#'

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    #'social.pipeline.user.get_username',
    'core.utils.require_email',
    #'social.pipeline.mail.mail_validation',
    'social.pipeline.social_auth.associate_by_email',
    'social.pipeline.user.create_user',
    #'core.utils.save_user_data',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
)

SOCIAL_AUTH_FACEBOOK_KEY = '1651426118459699'
SOCIAL_AUTH_FACEBOOK_SECRET = 'c5ca36931d7fecffdf0154628b49ba80'

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email',
}

SOCIAL_AUTH_TWITTER_KEY = '68syyl38vhgrQTGVV9afH14Wq'
SOCIAL_AUTH_TWITTER_SECRET = 'Z3UG5LWWjEkcV9N2EbRvgWotPTaaBtBCphnxGOLYXGX0PNNtgv'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '880205711592-hdqlbd2ur5e1ui92sa0o4235eonf57tn.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'AIzaSyDv045E6Z3sZ-915Kf5XqhvR4cWPYAz8kM'

SOCIAL_AUTH_USER_MODEL = AUTH_USER_MODEL

SOCIAL_AUTH_SLUGIFY_USERNAMES = True

SOCIAL_AUTH_SLUGIFY_FUNCTION = 'core.utils.username_to_uuid'

SWAGGER_SETTINGS = {
    "is_authenticated": True,  # Set to True to enforce user authentication,
    "is_superuser": True,  # Set to True to enforce admin only access
}

OPBEAT = {
    'ORGANIZATION_ID': '8e41e3be8eea4489b118bd9dff00188c',
    'APP_ID': '8db27a7c8f',
    'SECRET_TOKEN': 'd4a2f6ce3eaed82aadc646c3d374c0f09286291d',
}
OPBEAT_WEBSITE = {
    'ORGANIZATION_ID': '8e41e3be8eea4489b118bd9dff00188c',
    'APP_ID': '7632168fe6',
    'SECRET_TOKEN': 'd4a2f6ce3eaed82aadc646c3d374c0f09286291d',
}

ANDROID_VERSION_CODE = 58
IPHONE_VERSION_CODE = None
BILL_UPLOAD_CAMPAIGN = True
PAYMENT_GATEWAY_TO_USE = 2 # 1- Citrus, 2-Razorpay
BOTO_S3_BUCKET_BOOKING = 'unbox-bumper2-booking'
SHORT_URL_API_KEY = "AIzaSyAOT6cQqZ0VFkv65Z7NEJnSg3rAKk6XEHI"

if DEBUG:
    import logging
    l = logging.getLogger('django.db.backends')
    l.setLevel(logging.DEBUG)
    l.addHandler(logging.StreamHandler())

LOGGING_FOLDER = '/var/log/bumper2/'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'default': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_FOLDER + 'bump.log',
            'maxBytes': 1024*1024*100, # 100 MB
            'backupCount': 15,
            'formatter':'standard',
        },
        'script': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_FOLDER + 'scripts_bump.log',
            'maxBytes': 1024*1024*100, # 100 MB
            'backupCount': 15,
            'formatter': 'standard',
        },
        'request_handler': {
                'level':'DEBUG',
                'class':'logging.handlers.RotatingFileHandler',
                'filename': LOGGING_FOLDER + 'django_request.log',
                'maxBytes': 1024*1024*100, # 100 MB
                'backupCount': 15,
                'formatter':'standard',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
        'opbeat': {
            'level': 'ERROR',
            'class': 'opbeat.contrib.django.handlers.OpbeatHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['default', 'opbeat'],
            'level': 'DEBUG',
            'propagate': True
        },
        'bumper.scripts': {
            'handlers': ['script', 'opbeat'],
            'level': 'DEBUG',
            'propagate': False
        },
        'django': {
            'handlers': ['mail_admins'],
            'propagate': True,
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['request_handler'],
            'level': 'DEBUG',
            'propagate': False
        },
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console'],
        },
    }
}

#Android
LOCALYTICS_ANDROID_API_KEY = "7538defbb583b2640de0dc2-af993e68-23ed-11e6-44b0-00adad38bc8d"
LOCALYTICS_ANDROID_APP_SECRET = "6bf73d0bd5b9d46e5dc606d-af9941b0-23ed-11e6-44b0-00adad38bc8d"
LOCALYTICS_ANDROID_APP_ID = "6da143188750090d39e18b1-2028c6c4-23ee-11e6-5a68-0042876ec363"

#iphone
LOCALYTICS_IPHONE_API_KEY = ""
LOCALYTICS_IPHONE_APP_SECRET = ""
LOCALYTICS_IPHONE_APP_ID = "961731492009727eb0d9cb3-786be046-91dd-11e6-4a37-00f573af1d63"

GOOGLE_MAP_API_KEY_FOR_DISTANCE_MATRIX = 'AIzaSyCZuPNa7waiT1PRkIfxDHi09FN_gNJP75A'

SEND_STATUS_CHANGE_TO_LOCALYTICS = True
